import { Employee, Visit } from './types';

export const employees: Employee[] = [
  { id: 'emp-001', name: 'Arjun Mehta', department: 'Engineering', mobile: '+91 98765 43210', email: 'arjun@company.com' },
  { id: 'emp-002', name: 'Priya Sharma', department: 'HR', mobile: '+91 98765 43211', email: 'priya@company.com' },
  { id: 'emp-003', name: 'Rahul Gupta', department: 'Operations', mobile: '+91 98765 43212', email: 'rahul@company.com' },
  { id: 'emp-004', name: 'Sneha Patel', department: 'Finance', mobile: '+91 98765 43213', email: 'sneha@company.com' },
  { id: 'emp-005', name: 'Vikram Singh', department: 'Sales', mobile: '+91 98765 43214', email: 'vikram@company.com' },
  { id: 'emp-006', name: 'Anita Desai', department: 'Marketing', mobile: '+91 98765 43215', email: 'anita@company.com' },
  { id: 'emp-007', name: 'Karan Joshi', department: 'IT', mobile: '+91 98765 43216', email: 'karan@company.com' },
  { id: 'emp-008', name: 'Meera Nair', department: 'Research', mobile: '+91 98765 43217', email: 'meera@company.com' },
];

const generateOTP = () => Math.floor(100000 + Math.random() * 900000).toString();
const generateToken = () => crypto.randomUUID().replace(/-/g, '').slice(0, 24);

export const mockVisits: Visit[] = [
  {
    id: 'visit-001',
    visitorName: 'Elias Thorne',
    visitorCompany: 'Meridian Capital',
    visitorMobile: '+91 99887 76655',
    visitorType: 'visitor',
    purpose: 'Board Meeting',
    hostId: 'emp-001',
    hostName: 'Arjun Mehta',
    hostDepartment: 'Engineering',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '10:00',
    status: 'checked_in',
    otp: '482913',
    otpExpiresAt: new Date(Date.now() + 600000).toISOString(),
    secureToken: generateToken(),
    checkInTime: '09:58',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'visit-002',
    visitorName: 'Marcus Hayes',
    visitorCompany: 'TechVend Solutions',
    visitorMobile: '+91 99887 76656',
    visitorType: 'vendor',
    purpose: 'Server Maintenance',
    hostId: 'emp-007',
    hostName: 'Karan Joshi',
    hostDepartment: 'IT',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '11:00',
    status: 'approved',
    otp: '739201',
    otpExpiresAt: new Date(Date.now() + 600000).toISOString(),
    secureToken: generateToken(),
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'visit-003',
    visitorName: 'Dr. Aris Chen',
    visitorCompany: 'NovaBio Labs',
    visitorMobile: '+91 99887 76657',
    visitorType: 'visitor',
    purpose: 'Research Collaboration',
    hostId: 'emp-008',
    hostName: 'Meera Nair',
    hostDepartment: 'Research',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '14:00',
    status: 'pending',
    otp: generateOTP(),
    otpExpiresAt: new Date(Date.now() + 600000).toISOString(),
    secureToken: generateToken(),
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'visit-004',
    visitorName: 'Sarah Mitchell',
    visitorCompany: 'CloudNet Services',
    visitorMobile: '+91 99887 76658',
    visitorType: 'vendor',
    purpose: 'Network Audit',
    hostId: 'emp-007',
    hostName: 'Karan Joshi',
    hostDepartment: 'IT',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '09:30',
    status: 'checked_out',
    otp: '192837',
    otpExpiresAt: new Date(Date.now() - 600000).toISOString(),
    secureToken: generateToken(),
    checkInTime: '09:28',
    checkOutTime: '11:45',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'visit-005',
    visitorName: 'James Walker',
    visitorCompany: 'Apex Consulting',
    visitorMobile: '+91 99887 76659',
    visitorType: 'visitor',
    purpose: 'Client Presentation',
    hostId: 'emp-005',
    hostName: 'Vikram Singh',
    hostDepartment: 'Sales',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '15:30',
    status: 'approved',
    otp: generateOTP(),
    otpExpiresAt: new Date(Date.now() + 600000).toISOString(),
    secureToken: generateToken(),
    createdAt: new Date(Date.now() - 5400000).toISOString(),
  },
];
